site_name: "Crowds"
repo_url: "https://github.com/Placeholder-Software/Crowds"
repo_name: "Issue Tracker"
google_analytics: ["UA-46722926-6", "crowds.readthedocs.io"]
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
theme:
    name: mkdocs
    include_sidebar: false
nav:
- Home: "index.md"
- "Getting Started":
    - "Requirements": "GettingStarted/Requirements"
    - "Quick Start": "GettingStarted/QuickStart"
    - "Demo Scenes":
        - "Contents": "GettingStarted/DemoScenes/Contents"
        - "1. Basic Steering Behaviours": "GettingStarted/DemoScenes/Steering"
        - "2. Local Avoidance": "GettingStarted/DemoScenes/LocalAvoidance"
    - "Getting Help": "GettingStarted/Support.md"
- "How To":
    - "Create A New Agent": "HowTo/CreateAnAgent.md"
    - "Follow A Path": "HowTo/FollowPath.md"
- "Advanced":
    - "Custom Steering Behaviour": "Advanced/CustomSteering.md"
- "Reference":
    - "MonoBehaviours":
        - "Entity Identity": "Reference/EntityIdentity.md"
        - "Navigator": "Reference/Navigator.md"
        - "Local Avoidance":
            - "Urgency": "Reference/Urgency.md"
        - "Steering":
            - "SteerForArrival": "Reference/SteerForArrival.md"
            - "SteerForFlee": "Reference/SteerForFlee.md"
            - "SteerForEvade": "Reference/SteerForEvade.md"
            - "SteerForPursue": "Reference/SteerForPursue.md"
            - "SteerForGoal": "Reference/SteerForGoal.md"
            - "SteerForTargetSpeed": "Reference/SteerForTargetSpeed.md"
            - "SteerForWander": "Reference/SteerForWander.md"
    - "ECS Components":
        - "todo"
    - "ECS Systems":
        - "todo"

