site_name: "Crowds: Unity Path Following"
repo_url: "https://github.com/Placeholder-Software/Crowds"
repo_name: "Issue Tracker"
google_analytics: ["UA-46722926-6", "crowds.readthedocs.io"]
theme:
  name: mkdocs
  highlightjs: false
  custom_dir: theme
extra_css:
  - css/pygment_tweaks.css
use_directory_urls: false
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
markdown_extensions:
    - markdown.extensions.sane_lists
    - codehilite
nav:
- Home: "index.md"
- "Getting Started":
    - "Requirements": "GettingStarted/Requirements.md"
    - "Quick Start": "GettingStarted/QuickStart.md"
    - "Support/Issues": "GettingStarted/Support.md"
- "Demo Scenes":
    - "1. Basic Steering Behaviours": "Demo Scenes/Steering.md"
    - "2. Local Avoidance": "Demo Scenes/LocalAvoidance.md"
- "How To":
    - "Follow A Path": "How To/FollowPath.md"
- "Reference":
    - "Navigator": "Reference/Navigator.md"


