site_name: "Crowds"
repo_url: "https://github.com/Placeholder-Software/Crowds"
repo_name: "Issue Tracker"
google_analytics: ["UA-46722926-6", "crowds.readthedocs.io"]
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
theme:
    name: mkdocs
    include_sidebar: false
nav:
- Home: "index.md"
- "Getting Started":
    - "Requirements": "GettingStarted/Requirements.md"
    - "Quick Start": "GettingStarted/QuickStart.md"
    - "Demo Scenes":
        - "1. Basic Steering Behaviours": "GettingStarted/Demo Scenes/Steering.md"
        - "2. Local Avoidance": "GettingStarted/Demo Scenes/LocalAvoidance.md"
    - "Getting Help": "GettingStarted/Support.md"
- "How To":
    - "Follow A Path": "How To/FollowPath.md"
- "Advanced":
    - "Custom Steering Behaviour": "Advanced/CustomSteering.md"
- "Reference":
    - "Entity Identity": "Reference/EntityIdentity.md"
    - "Navigator": "Reference/Navigator.md"
    - "Stress": "Reference/Stress.md"
    - "Urgency": "Reference/Urgency.md"
    - "SteerForArrival": "Reference/SteerForArrival.md"
    - "SteerForEvade": "Reference/SteerForEvade.md"
    - "SteerForFlee": "Reference/SteerForFlee.md"
    - "SteerForGoal": "Reference/SteerForGoal.md"
    - "SteerForPursue": "Reference/SteerForPursue.md"
    - "SteerForTargetSpeed": "Reference/SteerForTargetSpeed.md"
    - "SteerForWander": "Reference/SteerForWander.md"
