site_name: "Crowds"
repo_url: "https://github.com/Placeholder-Software/Crowds"
repo_name: "Issue Tracker"
google_analytics: ["UA-46722926-6", "crowds.readthedocs.io"]
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
theme:
    name: mkdocs
    include_sidebar: false
markdown_extensions:
    - admonition
    - toc:
        # The character on the right of `permalink` is a little chain icon. Doesn't render properly in vscode for some reason.
        permalink: 
extra_css:
    - css/admonition.css
    - css/title-indent.css
nav:
- Home: "index.md"
- "Getting Started":
    - "Requirements": "GettingStarted/Requirements.md"
    - "Quick Start": "GettingStarted/QuickStart.md"
    - "What Is Local Avoidance?": "GettingStarted/LocalAvoidance.md"
    - "Demo Scenes":
        - "Contents": "GettingStarted/DemoScenes/Contents.md"
        - "1. Basic Steering Behaviours": "GettingStarted/DemoScenes/Steering.md"
        - "2. Local Avoidance": "GettingStarted/DemoScenes/LocalAvoidance.md"
    - "Getting Help": "GettingStarted/Support.md"
- "How To":
    - "Create A New Agent": "HowTo/CreateAnAgent.md"
    - "Follow A Path": "HowTo/FollowPath.md"
- "Advanced":
    - "Custom Steering Behaviour": "Advanced/CustomSteering.md"
- "Reference":
    - "MonoBehaviours":
        - "Entity Identity": "Reference/MonoBehaviours/EntityIdentity.md"
        - "Navigator": "Reference/MonoBehaviours/Navigator.md"
        - "Local Avoidance":
            - "Urgency": "Reference/MonoBehaviours/Urgency.md"
        - "Steering":
            - "SteerForArrival": "Reference/MonoBehaviours/SteerForArrival.md"
            - "SteerForFlee": "Reference/MonoBehaviours/SteerForFlee.md"
            - "SteerForEvade": "Reference/MonoBehaviours/SteerForEvade.md"
            - "SteerForPursue": "Reference/MonoBehaviours/SteerForPursue.md"
            - "SteerForGoal": "Reference/MonoBehaviours/SteerForGoal.md"
            - "SteerForTargetSpeed": "Reference/MonoBehaviours/SteerForTargetSpeed.md"
            - "SteerForWander": "Reference/MonoBehaviours/SteerForWander.md"
    - "ECS Components":
        - "todo"
    - "ECS Systems":
        - "todo"

