site_name: "Crowds"
repo_url: "https://github.com/Placeholder-Software/Crowds"
repo_name: "Issue Tracker"
google_analytics: ["UA-46722926-6", "crowds.readthedocs.io"]
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
theme:
    name: mkdocs
    include_sidebar: false
markdown_extensions:
    - admonition
    - toc:
        # The character on the right of `permalink` is a little chain icon. Doesn't render properly in vscode for some reason.
        permalink: 
extra_css:
    - css/admonition.css
    - css/title-indent.css
nav:
- "Home": "index.md"
- "Getting Started":
    - "Requirements": "GettingStarted/Requirements.md"
    - "Quick Start": "GettingStarted/QuickStart.md"
    - "What Are Steering Behaviours?": "GettingStarted/SteeringBehaviours.md"
    - "What Is Local Avoidance?": "GettingStarted/LocalAvoidance.md"
    - "Demo Scenes":
        - "Contents": "GettingStarted/DemoScenes/Contents.md"
        - "1. Basic Steering Behaviours": "GettingStarted/DemoScenes/Steering.md"
        - "2. Local Avoidance": "GettingStarted/DemoScenes/LocalAvoidance.md"
    - "Getting Help": "GettingStarted/Support.md"
- "How To":
    - "Create A New Agent": "HowTo/CreateAnAgent.md"
    - "Follow A Path": "HowTo/FollowPath.md"
    - "Build Formations":
        - "Roman Legion": "HowTo/Formations/Legion.md"
        - "Bodyguard/VIP": "HowTo/Formations/Bodyguard.md"
        - "Wolfpack": "HowTo/Formations/Wolfpack.md"
    - "Traverse Off-Mesh Links": "HowTo/TraverseOffMesh.md"
    - "Drive An Agent With Player Input": "HowTo/PlayerControl.md"
    - "Animate An Agent": "HowTo/AnimatedAgents.md"
    - "Find A Path": "HowTo/FindPath.md"
- "Advanced":
    - "Custom Steering Behaviour": "Advanced/CustomSteering.md"
    - "Pathfinding": "Advanced/Pathfinding.md"
#    - "Using The ECS": "Advanced/UseECS.md"
- "Reference":
#    - "MonoBehaviours":
        - "Entity Identity": "Reference/MonoBehaviours/EntityIdentity.md"
        - "Navigator": "Reference/MonoBehaviours/Navigator.md"
        - "Local Avoidance":
            - "Urgency": "Reference/MonoBehaviours/Urgency.md"
        - "Goal": "Reference/MonoBehaviours/Goal.md"
        - "Synchroniser": "Reference/MonoBehaviours/Synchroniser.md"
        - "Steering":
            - "SteerForArrival": "Reference/MonoBehaviours/SteerForArrival.md"
            - "SteerForFlee": "Reference/MonoBehaviours/SteerForFlee.md"
            - "SteerForEvade": "Reference/MonoBehaviours/SteerForEvade.md"
            - "SteerForPursue": "Reference/MonoBehaviours/SteerForPursue.md"
            - "SteerForGoal": "Reference/MonoBehaviours/SteerForGoal.md"
            - "SteerForTargetSpeed": "Reference/MonoBehaviours/SteerForTargetSpeed.md"
            - "SteerForTargetVelocity": "Reference/MonoBehaviours/SteerForTargetVelocity.md"
            - "SteerForWander": "Reference/MonoBehaviours/SteerForWander.md"
        - "Formations":
            - "Assign To Formation": "Reference/MonoBehaviours/AssignToFormation.md"
            - "Rectangle Grid": "Reference/MonoBehaviours/RectangleGridFormation.md"
        - "BaseComponentProxyBehaviour": "Reference/MonoBehaviours/BaseComponentProxyBehaviour.md"
        - "Pathfinding":
            - "PathfindingTask": "Reference/Other/PathfindingTask.md"
            - "PathfindingResult": "Reference/Other/PathfindingResult.md"
            - "PathfindingResultPolygon": "Reference/Other/PathfindingResultPolygon.md"
            - "PathfindingResultPortal": "Reference/Other/PathfindingResultPortal.md"
#    - "ECS Components":
#        - "stuff"
#    - "ECS Systems":
#        - "stuff"

